config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', {to: 'sessions#destroy'}
  post 'message', to: 'messages#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates(:username, presence: true, length: {minimum: 3, maximum: 15},
    uniqueness: {case_sensitive: false})
  has_secure_password()
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method(:logged_in?)

  def logged_in?
    !!current_user
  end

  def log_in(user)
    session[:user_id] = user.id
    flash[:success] = "You have logged in"
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def log_out
    session[:user_id] = nil
    @current_user = nil
    flash[:success] = "You have logged out"
  end

  def require_user
    if (!logged_in?)
      flash[:error] = "You need to be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  before_action(:require_user)

  def index
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if (message.save)      
    else
      flash[:error] = "Message was not saved"
    end
    redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action(:logged_in_redirect, only: [:new, :create])

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if (user && user.authenticate(params[:session][:password]))
      log_in(user)
      flash[:success] = "You have successfuly loged in"
      redirect_to root_path
    else
      flash.now[:error] = "The login was not successful"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/_chatarea.html.erb
<div class="ui fluid raised card chatbox">
  <div class="content">
    <div class="ui feed">

      <%= render partial: "chatroom/messages", collection: @messages, as: :message %>
    </div>
  </div>
  <div class="extra content">
    <%= form_for(@message, {html: {class: "ui reply form", role: "form"}, url: message_path}) do |f| %>
      <div class="field">
        <div class="ui fluid icon input">
          <%=  f.text_field :body %>
          <%= f.button '<i class="boerdered inverted blue icon edit"></i>'.html_safe %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/chatroom/_menu.html.erb
<div class="ui fluid raised card chatbox">
  <div class="content">
    <div class="ui inverted vertical menu">
      <a class="active item">
        Home
      </a>
      <a class="item">
        Messages
      </a>
      <a class="item">
        Friends
      </a>
    </div>
  </div>
</div>

app/views/chatroom/_messages.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
       <em> <%= message.user.username %> </em> : <%= message.body %>
    </div>
  </div>
</div>

app/views/chatroom/index.html.erb
<%= render 'layouts/header_icon', {text: "Best Chat App"} %>
<div class="ui two column grid">
  <div class="twelve wide column">
    <%= render 'chatroom/chatarea' %>
  </div>
  <div class="four wide column">
    <%= render 'chatroom/menu' %>
  </div>
</div>

app/views/layouts/_header_icon.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular umbrella icon blue"></i>
  <%= text %>
</h4>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, {class: "item"} %>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <%= link_to "Admin cheat", login_path(:session => {
          :username=>"Admin", :password=> "password"}),
             {method: :post, class: "item"} if !logged_in? %>

      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
              <%= link_to "Logout", logout_path,
                  {method: :delete, class: "item"} %>
          <% else %>
            <%= link_to "Login", login_path, {class: "item"} %>
          <% end %>
        </div>
      </div>
      <div class="item">          
          <%= link_to "Sign up", "#", {class: "ui primary button"}  if !logged_in? %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageingApp2</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'shared/flash' %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="ui <%= "#{name}" %> message flash">
    <i class="close icon"></i>
    <div class="header">
      <%= msg %>
    </div>
  </div>
<% end %>